server:
  port: 8080
  servlet:
    context-path: /TECHNICALTEST

spring:
  messages:
    basename: messages
    encoding: UTF-8
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/technical-test-supralog
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    hikari:
      minimumIdle: 5
      maximumPoolSize: 20
      idleTimeout: 30000
      maxLifetime: 2000000
      connectionTimeout: 30000
  flyway:
    table: schema_version
    enabled: false
